import os

from sqlalchemy.orm import Session

from src.models.report import Report
from src.repositories.report_repository import ReportRepository
from src.schemas.report import ReportCreate


class ReportService:
    """
    Business logic for report management.
    """

    def __init__(self, db: Session):
        self.repository = ReportRepository(db)

    def create_report(
        self,
        report_data: ReportCreate,
    ) -> Report:
        """
        Create a new report.
        """

        report = Report(
            report_type=report_data.report_type,
            file_name=report_data.file_name,
            file_path=report_data.file_path,
            generated_by=report_data.generated_by,
        )

        return self.repository.create(report)

    def list_reports(self):
        """
        Return all reports.
        """

        return self.repository.get_all()

    def get_report(
        self,
        report_id: int,
    ):
        """
        Return report by ID.
        """

        return self.repository.get_by_id(report_id)

    def get_user_reports(
        self,
        user_id: int,
    ):
        """
        Return reports generated by a user.
        """

        return self.repository.get_by_user(user_id)

    def get_reports_by_type(
        self,
        report_type: str,
    ):
        """
        Return reports by report type.
        """

        return self.repository.get_by_type(report_type)

    def delete_report(
        self,
        report_id: int,
    ):
        """
        Delete report and remove file from storage.
        """

        report = self.repository.get_by_id(report_id)

        if report is None:
            return False

        if os.path.exists(report.file_path):
            os.remove(report.file_path)

        self.repository.delete(report)

        return True
