from sqlalchemy.orm import Session

from src.models.report import Report


class ReportRepository:
    """
    Handles database operations for reports.
    """

    def __init__(self, db: Session):
        self.db = db

    def create(
        self,
        report: Report,
    ) -> Report:
        """
        Save a report.
        """

        self.db.add(report)
        self.db.commit()
        self.db.refresh(report)

        return report

    def get_all(self):
        """
        Return all reports.
        """

        return self.db.query(Report).order_by(Report.created_at.desc()).all()

    def get_by_id(
        self,
        report_id: int,
    ):
        """
        Return report by ID.
        """

        return self.db.query(Report).filter(Report.id == report_id).first()

    def get_by_user(
        self,
        user_id: int,
    ):
        """
        Return reports generated by a user.
        """

        return (
            self.db.query(Report)
            .filter(Report.generated_by == user_id)
            .order_by(Report.created_at.desc())
            .all()
        )

    def get_by_type(
        self,
        report_type: str,
    ):
        """
        Return reports by type.
        """

        return (
            self.db.query(Report)
            .filter(Report.report_type == report_type)
            .order_by(Report.created_at.desc())
            .all()
        )

    def delete(
        self,
        report: Report,
    ):
        """
        Delete a report.
        """

        self.db.delete(report)
        self.db.commit()
