"""create recordings table

Revision ID: 955eb3558093
Revises: 4a88ac2e10b5
Create Date: 2026-07-23 22:47:12.143177

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "955eb3558093"
down_revision: Union[str, Sequence[str], None] = "4a88ac2e10b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
